spring.application.name=backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/reco_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database=PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Secret Key
security.jwt.secret.key="f7a37dbc824a3cb3c76ff2900df8907103c31aa6ce0d829cb6b4fa0a2637700d"
security.jwt.access-expiration-time=900000
security.jwt.refresh-expiration-time=604800000
